### PR TITLE
T/ci and composer

### PR DESCRIPTION
**Pull request by till**

### CODE REVIEW

**Comment by cweiske** [comment]
@till  - why do we need the additional repository in `composer.json`, and why do we need `composer.lock` here - it's a library after all; I don't see the need for the lock file.

**Comment by till** [comment]
@cweiske Repo because the deps are not yet all on packagist.org. Lockfile because you want consistent dependencies for developers, contributors, etc..

**Comment by cweiske** [comment]
about composer.lock: I'd rather have CI, developers and contributers find bugs with other versions of the dependencies :)

About the deps: If validate is not on packagist, we have to bring it there.

**Comment by cweiske** [comment]
Validate 0.8.5 is on packagist now: https://packagist.org/packages/pear/validate

**Comment by cweiske** [comment]
Merged.

**Pull request closed without merging**
